import { describe, test, expect } from "@jest/globals";
import {
  generateTokens,
  verifyRefreshToken,
} from "../../src/utils/generateTokens.js";

const fakeUser = {
  _id: "507f1f77bcf86cd799439011",
  role: "vendor",
};

describe("generateTokens / verifyRefreshToken", () => {
  test("generates an access and refresh token", () => {
    const { accessToken, refreshToken } = generateTokens(fakeUser);

    expect(typeof accessToken).toBe("string");
    expect(typeof refreshToken).toBe("string");
    expect(accessToken).not.toEqual(refreshToken);
  });

  test("verifyRefreshToken decodes a token generated by generateTokens", () => {
    const { refreshToken } = generateTokens(fakeUser);

    const decoded = verifyRefreshToken(refreshToken);

    expect(decoded.sub).toBe(fakeUser._id);
  });

  test("verifyRefreshToken throws on a garbage token", () => {
    expect(() => verifyRefreshToken("not-a-real-token")).toThrow();
  });

  test("access token embeds the user's role as a claim", () => {
    const { accessToken } = generateTokens(fakeUser);

    const payload = JSON.parse(
      Buffer.from(accessToken.split(".")[1], "base64").toString(),
    );

    expect(payload.role).toBe("vendor");
    expect(payload.sub).toBe(fakeUser._id);
  });
});
